
name: GitHub → Dropbox Auto-App Merge

on:
  push:
    paths:
      - '**.tar.gz'
      - '**.tgz'

jobs:
  merge-to-dropbox:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run merge script
        env:
          DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
        run: python scripts/merge.py
