name: Upload to Dropbox

on:
  push:
    branches: [ main ]
    paths:
      - '*.tar.gz'
      - '*.tgz'
      - '*.tar'  # Add this line to watch for .tar files
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dropbox requests
        
    - name: List files (debug)
      run: ls -la
      
    - name: Run update script
      run: python upload_to_dropbox.py
      env:
        DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
        
    - name: Verify upload
      run: |
        echo "Checking results..."
        if [ -f upload.log ]; then
          cat upload.log
        fi
