name: Upload .tgz to Master Tar

on:
  push:
    branches: [ main ]
    paths:
      - '*.tgz'  # Now only watching for .tgz files
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dropbox requests
        
    - name: Run update script
      run: |
        echo "=== Starting .tgz to master tar update ==="
        python upload_to_dropbox.py
      env:
        DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
        
    - name: Show logs
      if: always()
      run: |
        echo "=== Upload Log Output ==="
        if [ -f upload.log ]; then
          cat upload.log
        else
          echo "No upload.log found"
        fi
